### ISSUE TITLE
Add custom property on the event object to get the original currentTarget

### ISSUE THREAD

**Issue by janwidmer** [namics/gondel#11]
With the events all being attached to the html, when having an event handler, the property `even.currentTarget` always returns the html element. 

Quite often, the element which triggers the event contains sub elements. E.g. a button containing a span. When you need to be sure, that you get the button element within your event handler, you currently need to add some extra logic, see stackblitz for details: https://stackblitz.com/edit/gondel-target-vs-currenttarget

Extend the event object to have a custom property on it which contains the original currentTarget, e.g. the element, which the event was added onto.

**Comment by jantimon** [comment]
We should probably do sth similar to react and create a synthetic event object.

Maybe sth like this:

```
const syntaticEvent = Object.create(event);
syntaticEvent.originalEvent = event;

// loop through listeners 
syntheticEvent.currentTarget = element;
```

That should be quite fast by using prototype inheritance- what do you think?

**Comment by jantimon** [comment]
Looked a little bit more into it together with @janbiasi and there are some browser limitations.

A possible solution is based on the following [stackoverflow question](https://stackoverflow.com/questions/52057726/what-is-the-best-way-to-alter-a-native-browser-event):

```
// loop through listeners 
Object.defineProperty(event, "currentTarget", {
  value: element,
  configurable: true
});

// cleanup
delete(event.currentTarget)
```

**Comment by janwidmer** [comment]
Tested in IE11 on Windows 7 and sadly seems not to work, see https://stackblitz.com/edit/gondel-target-vs-currenttarget

**Comment by jantimon** [comment]
It looks like the underlying api from [this stackoverflow answer](https://stackoverflow.com/questions/52057726/what-is-the-best-way-to-alter-a-native-browser-event) works for:

- Chrome
- Firefox
- IE Edge
- IE 11

See here: https://jsbin.com/bimuxiyinu/1/edit?html,console,output

Output Chrome:
<img width="328" alt="chrome" src="https://user-images.githubusercontent.com/4113649/47985535-2e5ae000-e0da-11e8-8192-010edef60ca5.png">


Output IE:
<img width="302" alt="ie11" src="https://user-images.githubusercontent.com/4113649/47985520-2307b480-e0da-11e8-94b6-676d9e588e97.png">

Output FF:
<img width="281" alt="ff" src="https://user-images.githubusercontent.com/4113649/47985591-67935000-e0da-11e8-815c-9bcd135d6da2.png">

Output Safari:
<img width="277" alt="safari" src="https://user-images.githubusercontent.com/4113649/47985573-5ba78e00-e0da-11e8-9ee2-887d189f705f.png">

**Comment by jantimon** [comment]
@janwidmer now it seems to be fixed:
<img width="1666" alt="fixed" src="https://user-images.githubusercontent.com/4113649/47991091-75040680-e0e9-11e8-889a-45d9b78e4f13.png">
