### ISSUE TITLE
Update documentation and examples to get ready for 1.0 release

### ISSUE THREAD

**Issue by janwidmer** [namics/gondel#54]
## Type of issue

* Documentation issue or request

The issue refers to:

* the gondel core
* a gondel plugin

----

Update documentation and examples to get ready for 1.0 release

**Comment by jegli** [comment]
I suppose this issue can be closed with the release of version 1.0.0 👍
Congats for the good work, both the documentation 📘 and the hook support for the react-plugin  🎉

**Comment by ernscht** [comment]
That's right. Release party.  🎉
@jegli Thanks for the hint.
