### ISSUE TITLE
Core changes: add generic typings for DOM utils, refactor componentName location amm.

### ISSUE THREAD

**Issue by janbiasi** [namics/gondel#6]
## Description 
If you want to get a component by DOM node (e.g. child component "MyButton") you have to cast the element with the `as ...` operator. We could add generic typings to the utilities to provide a simple API to automatically cast the "any" component to the right component class.

### Example

```js
import MyButton from './MyButton';

export class App extends React.Component<Props, {}> {
  private buttonRef: Element;
  private buttonComponent: MyButton;

  componentDidMount() {
    startComponents(this.buttonRef);
    // current way: getComponentByDomNode(this.buttonRef) as MyButton;
    this.buttonComponent = getComponentByDomNode<MyButton>(this.buttonRef)!;
    this.buttonComponent._ctx.addEventListener('click', () => alert('Hey!'));
  }

  render() {
     return (
       <h2>Hello World</h2>
       <MyButton text="Say hello!" ref=(ref => this.buttonRef = ref) />
     );
  }
}
```

**Comment by janbiasi** [comment]
Hey @jantimon what do you think of the method to add the `componentName` to the class as static value instead of passing it to the decorator? So this would be enable us to access the mapping to the DOM in each function and other utilities than passing it to all methods everytime.

Example is under [GondelDecorators.ts#L10](https://github.com/namics/gondel/blob/feature/generic-dom-utils/packages/core/src/GondelDecorators.ts#L10 ) and [GondelComponentRegistry.ts#L43](https://github.com/namics/gondel/blob/feature/generic-dom-utils/packages/core/src/GondelComponentRegistry.ts#L43)

Another benefit would be that we eventually could replace all "componentName" parameters for e.g. `findComponents(node, componentName, ns = 'g')` and this would enable us to automatically type the output of the `findComponents` method, example below:

```js
// current way to find components
findComponents(document.documentElement, 'Button') as Array<Button>;

// with the static class value (idea) we have the componentName ('Button') and the typing
findComponents(document.documentElement, Button);
```

Thanks for the response!

**Comment by jantimon** [comment]
Hey Jan - I am looking forward to our in person meeting tomorrow.  
Both ideas are really really cool.

Maybe we can achieve your ideas even without introducing breaking changes! :)

**Comment by janbiasi** [comment]
To prevent the breaking change is simple if we enable the option to set the static `componentName` or set the static property via decorator parameter - the only thing which is getting more difficult is to provide a great typechecking experience because its - i think - at the moment not possible to say "you must set the static property or the first parameter in the decorator" ... 

We can discuss this point tomorrow at our meeting 😸

**Comment by janbiasi** [comment]
@jantimon what should we do with this approach? just ignore it for the moment? 😃

**Comment by janwidmer** [comment]
Closed due to inactivity.
